import 'package:futurebuilder_demo/api/services_api.dart';
import 'package:futurebuilder_demo/models/Autogenerated.dart';
import 'package:get/get.dart';

// ignore: camel_case_types
class controller extends GetxController {
  var getmodeldata = Autogenerated().obs; //model class obx controller
  var isLoading = true.obs;
  services_api request = services_api();

  @override
  void onInit() {
    callFormodelData();
    super.onInit();
  }

  void callFormodelData() async {
    try {
      isLoading.value = true;
      var result = await request.autogeneratedDemo();
      getmodeldata.value = result;
    } finally {
      isLoading.value = false;
    }
  }
}
