// ignore_for_file: public_member_api_docs, sort_constructors_first

import 'package:flutter/material.dart';
import 'package:futurebuilder_demo/models/Autogenerated.dart';
import 'package:futurebuilder_demo/models/Persional.dart';

// ignore: camel_case_types
class itemWidget extends StatelessWidget {
  final Persional user;
  const itemWidget({
    Key? key,
    required this.user,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Container(
        height: 60,
        margin: const EdgeInsets.all(10),
        padding: const EdgeInsets.all(10),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          color: Colors.white,
        ),
        child: Row(
          children: [
            Container(
              clipBehavior: Clip.hardEdge,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10),
                color: Colors.white,
              ),
              child: Image.network(
                user.image,
                height: 40.0,
                width: 40.0,
              ),
            ),
            Expanded(
              child: Container(
                height: 60,
                margin: const EdgeInsets.fromLTRB(20, 0, 0, 0),
                color: Colors.white,
                alignment: Alignment.centerLeft,
                child: Text(
                  user.email,
                  style: const TextStyle(
                      color: Colors.black, fontWeight: FontWeight.bold),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
